### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davidfetter** [PDCRL/ConcurrentGraphDS#1]
Under what license are you publishing this code?  Please clarify.

**Comment by nandini12396** [comment]
Just added the GPL license to the repo. Thanks! Closing the issue.

**Comment by davidfetter** [comment]
Any chance of a less restrictive license like MIT?

**Comment by nandini12396** [comment]
alright, updated!

**Comment by davidfetter** [comment]
Thanks very much!
